spring:
  datasource:
    username: "${DB_USER}"
    password: "${DB_PASS}"
    url: "${DB_URL}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
